version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - .:/app
      - /app/build
      - /app/.gradle
    restart: always
    command: java -jar ./build/libs/play-tino-0.0.1-SNAPSHOT.jar